<a href="https://colab.research.google.com/github/jorgeponcer-svg/Series-Temporales/blob/main/Yahoo_Finance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Yahoo Finance
Si quieres tener los datos de precios de índices actualizados a día de hoy, lo puedes hacer de la siguiente manera. Estos datos han sido obtenidos mediante [Yahoo Finance](https://es.finance.yahoo.com/), una plataforma donde puedes ver, obtener, estudiar, analizar y comparar los precios de cierre de diferentes de acciones de los mercados financieros. La forma de obtener los datos de Yahoo Finance en Python es mediante el paquete `yfinance` que tendremos que instalar e importar.

In [ ]:
!pip install yfinance
import yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.13/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.13.4)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.5.3)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.16.3)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (6.33.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (3.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2026.7.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.3.0->yfinance) (2026.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.11)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

Para obtener los precios de cierre de los índices SP500, FTSE, DAX y NIKKEI, especificar los nombres, la fecha de inicio y fin, y el intervalo (diario=1d):

In [ ]:
raw_data = yfinance.download (tickers = "^GSPC ^FTSE ^N225 ^GDAXI", start = "2015-01-07",
                              end = "2020-05-17", interval = "1d", group_by = 'ticker', auto_adjust = True, threads = True)

[*********************100%***********************]  4 of 4 completed

In [ ]:
raw_data.tail()

                  ^GSPC               ...        ^FTSE
                   Open         High  ...        Close        Volume
Date                                  ...
2020-05-11  2915.459961  2944.250000  ...  5939.700195  1.041394e+09
2020-05-12  2939.500000  2945.820068  ...  5994.799805  9.397677e+08
2020-05-13  2865.860107  2874.139893  ...  5904.100098  1.055706e+09
2020-05-14  2794.540039  2852.800049  ...  5741.500000  1.152460e+09
2020-05-15  2829.949951  2865.010010  ...  5799.799805  9.274333e+08

[5 rows x 20 columns]

In [ ]:
df_comp=raw_data.copy()

Para cada día y cada precio obtenemos 4 datos, los precios de: apertura, máximo, bajo, cierre y volumen. Queremos los precios de cierre así que seleccionamos sólo la variable cierre para cada precio, los guardamos en 4 nuevas variables en el dataset y les ponemos los nombres del indice al que corresponden.

In [ ]:
df_comp['spx'] = df_comp['^GSPC'].Close[:]
df_comp['dax'] = df_comp['^GDAXI'].Close[:]
df_comp['ftse'] = df_comp['^FTSE'].Close[:]
df_comp['nikkei'] = df_comp['^N225'].Close[:]

In [ ]:
df_comp.head()

Ticker             ^N225                                            \
Price               Open          High           Low         Close
Date
2015-01-07  16808.259766  16974.609375  16808.259766  16885.330078
2015-01-08  17067.400391  17243.710938  17016.089844  17167.099609
2015-01-09  17318.740234  17342.650391  17129.529297  17197.730469
2015-01-12           NaN           NaN           NaN           NaN
2015-01-13  16970.880859  17087.710938  16828.269531  17087.710938

Ticker                        ^GDAXI                                         \
Price            Volume         Open         High          Low        Close
Date
2015-01-07  138600000.0  9510.339844  9592.370117  9459.179688  9518.179688
2015-01-08  140600000.0  9643.769531  9855.429688  9607.900391  9837.610352
2015-01-09  155200000.0  9813.990234  9860.179688  9601.750000  9648.500000
2015-01-12          NaN  9697.459961  9815.959961  9622.320312  9781.900391
2015-01-13  149200000.0  9759.570312  9978.940430  9755.019531  9941.000000

Ticker                   ...         ^GSPC        ^FTSE               \
Price            Volume  ...        Volume         Open         High
Date                     ...
2015-01-07   82466600.0  ...  3.805480e+09  6366.500000  6459.700195
2015-01-08  114825000.0  ...  3.934010e+09  6419.799805  6580.799805
2015-01-09  107473400.0  ...  3.364140e+09  6570.000000  6570.200195
2015-01-12  101315800.0  ...  3.456460e+09  6501.100098  6542.399902
2015-01-13  116360600.0  ...  4.107300e+09  6501.399902  6558.799805

Ticker                                                     spx          dax  \
Price               Low        Close       Volume
Date
2015-01-07  6366.500000  6419.799805  688211500.0  2025.900024  9518.179688
2015-01-08  6419.799805  6570.000000  882740200.0  2062.139893  9837.610352
2015-01-09  6471.399902  6501.100098  738488500.0  2044.810059  9648.500000
2015-01-12  6447.899902  6501.399902  602313100.0  2028.260010  9781.900391
2015-01-13  6465.200195  6542.200195  673572900.0  2023.030029  9941.000000

Ticker             ftse        nikkei
Price
Date
2015-01-07  6419.799805  16885.330078
2015-01-08  6570.000000  17167.099609
2015-01-09  6501.100098  17197.730469
2015-01-12  6501.399902           NaN
2015-01-13  6542.200195  17087.710938

[5 rows x 24 columns]

Pre-procesado: eliminar las variables que sobran, arreglar la frecuencia a business days y rellenar datos faltantes.

In [ ]:
df_comp = df_comp.iloc[1:]
# Seleccionamos únicamente las columnas que nos interesan de forma limpia y segura
df_comp = df_comp[['spx', 'dax', 'ftse', 'nikkei']]
df_comp = df_comp.asfreq('b')
df_comp = df_comp.ffill()

In [ ]:
df_comp.head()

                   spx          dax         ftse        nikkei

Date
1994-01-10  475.269989  2225.000000  3440.600098  18443.439453
1994-01-11  474.130005  2228.100098  3413.800049  18485.250000
1994-01-12  474.170013  2182.060059  3372.000000  18793.880859
1994-01-13  472.470001  2142.370117  3360.000000  18577.259766
1994-01-14  474.910004  2151.050049  3400.600098  18973.699219